/**
 * Map node label → Salesforce metadata API type used in package.xml.
 * Covers the ~30 most-common metadata types Phase 6 ships parsers for.
 */
export const LABEL_TO_METADATA_TYPE: Record<string, string> = {
  ApexClass: "ApexClass",
  ApexTrigger: "ApexTrigger",
  ApexPage: "ApexPage",
  ApexComponent: "ApexComponent",
  LightningComponentBundle: "LightningComponentBundle",
  AuraDefinitionBundle: "AuraDefinitionBundle",
  Flow: "Flow",
  CustomObject: "CustomObject",
  CustomField: "CustomField",
  Profile: "Profile",
  PermissionSet: "PermissionSet",
  PermissionSetGroup: "PermissionSetGroup",
  SharingRule: "SharingRules",
  NamedCredential: "NamedCredential",
  ExternalServiceRegistration: "ExternalServiceRegistration",
  PlatformEventChannel: "PlatformEventChannel",
  CustomLabel: "CustomLabels",
  CustomMetadataType: "CustomObject",
  CustomMetadataRecord: "CustomMetadata",
  StaticResource: "StaticResource",
  Layout: "Layout",
  RecordType: "RecordType",
  ValidationRule: "ValidationRule",
  Workflow: "Workflow",
  WorkflowRule: "WorkflowRule",
  ApprovalProcess: "ApprovalProcess",
  Queue: "Queue",
  Group: "Group",
  Role: "Role",
  ConnectedApp: "ConnectedApp",
  RemoteSiteSetting: "RemoteSiteSetting",
  EmailTemplate: "EmailTemplate",
  Report: "Report",
  Dashboard: "Dashboard",
  FlexiPage: "FlexiPage",
  DuplicateRule: "DuplicateRule",
  MatchingRule: "MatchingRules",
  Network: "Network",
  GenAiPlanner: "GenAiPlanner",
  GenAiPlugin: "GenAiPlugin",
};
