export const METADATA_CATEGORY = {
  APEX_CLASS: "ApexClass",
  APEX_TRIGGER: "ApexTrigger",
  APEX_PAGE: "ApexPage",
  APEX_COMPONENT: "ApexComponent",
  LWC: "LightningComponentBundle",
  AURA: "AuraDefinitionBundle",
  FLOW: "Flow",
  OBJECT: "CustomObject",
  FIELD: "CustomField",
  PROFILE: "Profile",
  PERMISSION_SET: "PermissionSet",
  PERMISSION_SET_GROUP: "PermissionSetGroup",
  SHARING_RULE: "SharingRule",
  NAMED_CREDENTIAL: "NamedCredential",
  EXTERNAL_CREDENTIAL: "ExternalCredential",
  EXTERNAL_SERVICE_REGISTRATION: "ExternalServiceRegistration",
  PLATFORM_EVENT: "PlatformEventChannel",
  CUSTOM_METADATA: "CustomMetadata",
  CUSTOM_LABEL: "CustomLabel",
  STATIC_RESOURCE: "StaticResource",
  LAYOUT: "Layout",
  RECORD_TYPE: "RecordType",
  VALIDATION_RULE: "ValidationRule",
  WORKFLOW: "Workflow",
  APPROVAL_PROCESS: "ApprovalProcess",
  QUEUE: "Queue",
  GROUP: "Group",
  ROLE: "Role",
  CONNECTED_APP: "ConnectedApp",
  REMOTE_SITE_SETTING: "RemoteSiteSetting",
  EMAIL_TEMPLATE: "EmailTemplate",
  REPORT: "Report",
  DASHBOARD: "Dashboard",
  OMNI_PROCESS: "OmniProcess",
  OMNI_DATA_TRANSFORM: "OmniDataTransform",
  OMNI_UI_CARD: "OmniUiCard",
  OMNI_INTEGRATION_PROCEDURE: "OmniIntegrationProcedure",
  VLOCITY_DATARAPTOR: "VlocityDataRaptor",
  VLOCITY_INTEGRATION_PROCEDURE: "VlocityIntegrationProcedure",
  VLOCITY_OMNISCRIPT: "VlocityOmniScript",
  VLOCITY_CARD: "VlocityCard",
  VLOCITY: "Vlocity",
  OMNISTUDIO: "OmniStudio",
  SECURITY: "Security",
  INTEGRATION: "Integration",
  // Phase 6 long-tail
  LIGHTNING_PAGE: "FlexiPage",
  GEN_AI_PLANNER: "GenAiPlanner",
  GEN_AI_PLUGIN: "GenAiPlugin",
  NETWORK: "Network",
  DUPLICATE_RULE: "DuplicateRule",
  MATCHING_RULE: "MatchingRule",
  CUSTOM_METADATA_TYPE: "CustomMetadataType",
  OPAQUE: "OpaqueMetadata",
} as const;

export type MetadataCategory = (typeof METADATA_CATEGORY)[keyof typeof METADATA_CATEGORY];
