export const REL_TYPES = {
  // Phase 0/1 (kept for backcompat)
  READS_FIELD: "READS_FIELD",
  WRITES_FIELD: "WRITES_FIELD",
  CALLS: "CALLS",
  CALLS_DR: "CALLS_DR",
  EXTENDS: "EXTENDS",
  IMPLEMENTS: "IMPLEMENTS",
  REFERENCES: "REFERENCES",
  CONTAINS: "CONTAINS",
  USES_LWC: "USES_LWC",
  TRIGGERS_ON: "TRIGGERS_ON",
  GRANTS: "GRANTS",
  QUERIES: "QUERIES",

  // Apex
  OVERRIDES: "OVERRIDES",
  CONTAINS_METHOD: "CONTAINS_METHOD",
  EXECUTES_SOQL: "EXECUTES_SOQL",
  EXECUTES_DML: "EXECUTES_DML",
  EXECUTES_SOSL: "EXECUTES_SOSL",
  INVOKES_REMOTE_ACTION: "INVOKES_REMOTE_ACTION",
  CALLS_NAMED_CREDENTIAL: "CALLS_NAMED_CREDENTIAL",
  IS_TEST_FOR: "IS_TEST_FOR",

  // LWC
  IMPORTS_APEX: "IMPORTS_APEX",
  USES_WIRE: "USES_WIRE",
  CALLS_APEX_FROM_LWC: "CALLS_APEX_FROM_LWC",
  IMPORTS_STATIC_RESOURCE: "IMPORTS_STATIC_RESOURCE",
  IMPORTS_CUSTOM_LABEL: "IMPORTS_CUSTOM_LABEL",
  DISPATCHES_EVENT: "DISPATCHES_EVENT",
  LISTENS_TO_EVENT: "LISTENS_TO_EVENT",
  EMBEDS_LWC: "EMBEDS_LWC",
  EMBEDS_AURA: "EMBEDS_AURA",
  CONTAINS_COMPONENT: "CONTAINS_COMPONENT",

  // Flow
  FLOW_INVOKES_APEX: "FLOW_INVOKES_APEX",
  FLOW_INVOKES_SUBFLOW: "FLOW_INVOKES_SUBFLOW",
  FLOW_INVOKES_ACTION: "FLOW_INVOKES_ACTION",
  REFERENCES_OBJECT: "REFERENCES_OBJECT",
  TRIGGER_FIRES_ON: "TRIGGER_FIRES_ON",

  // Object
  DEFINES_FIELD: "DEFINES_FIELD",
  HAS_RECORD_TYPE: "HAS_RECORD_TYPE",
  HAS_VALIDATION_RULE: "HAS_VALIDATION_RULE",

  // Vlocity
  DR_READS_FIELD: "DR_READS_FIELD",
  DR_WRITES_FIELD: "DR_WRITES_FIELD",
  DR_TRANSFORMS: "DR_TRANSFORMS",
  IP_CALLS_DR: "IP_CALLS_DR",
  IP_CALLS_IP: "IP_CALLS_IP",
  IP_INVOKES_REMOTE: "IP_INVOKES_REMOTE",
  OS_USES_DR: "OS_USES_DR",
  OS_CALLS_IP: "OS_CALLS_IP",
  OS_EMBEDS_VC: "OS_EMBEDS_VC",
  OS_INVOKES_REMOTE: "OS_INVOKES_REMOTE",
  VC_USES_DR: "VC_USES_DR",
  VC_CALLS_IP: "VC_CALLS_IP",
  EMBEDS_VC: "EMBEDS_VC",
  VC_EMBEDS_LWC: "VC_EMBEDS_LWC",
  VC_INVOKES_REMOTE: "VC_INVOKES_REMOTE",

  // OmniStudio
  OMNI_CALLS_DATA_TRANSFORM: "OMNI_CALLS_DATA_TRANSFORM",
  OMNI_CALLS_INTEGRATION_PROCEDURE: "OMNI_CALLS_INTEGRATION_PROCEDURE",
  OMNI_EMBEDS_UI_CARD: "OMNI_EMBEDS_UI_CARD",
  OMNI_INVOKES_REMOTE: "OMNI_INVOKES_REMOTE",
  OMNI_USES_DATA_TRANSFORM: "OMNI_USES_DATA_TRANSFORM",

  // Security
  GRANTS_OBJECT_ACCESS: "GRANTS_OBJECT_ACCESS",
  GRANTS_FIELD_ACCESS: "GRANTS_FIELD_ACCESS",
  GRANTS_APEX_ACCESS: "GRANTS_APEX_ACCESS",
  GRANTS_PAGE_ACCESS: "GRANTS_PAGE_ACCESS",
  GRANTS_TAB_ACCESS: "GRANTS_TAB_ACCESS",
  SHARING_GRANTS: "SHARING_GRANTS",
  SHARING_TO_GROUP: "SHARING_TO_GROUP",
  SHARING_TO_ROLE: "SHARING_TO_ROLE",
  SHARING_FROM_OWNER_GROUP: "SHARING_FROM_OWNER_GROUP",

  // Integration
  ESR_USES_NAMED_CREDENTIAL: "ESR_USES_NAMED_CREDENTIAL",
  PUBLISHES_EVENT: "PUBLISHES_EVENT",
  SUBSCRIBES_TO_EVENT: "SUBSCRIBES_TO_EVENT",

  // Cross-flavor
  CANONICAL_OF: "CANONICAL_OF",

  // Phase 6 long-tail
  CONTROLLED_BY: "CONTROLLED_BY",
  EXTENDS_CONTROLLER: "EXTENDS_CONTROLLER",
  RENDERS_FIELD: "RENDERS_FIELD",
  REPORTS_ON: "REPORTS_ON",
  DASHBOARD_USES_REPORT: "DASHBOARD_USES_REPORT",
  PLANNER_USES_PLUGIN: "PLANNER_USES_PLUGIN",
  PLUGIN_INVOKES_FUNCTION: "PLUGIN_INVOKES_FUNCTION",
  NETWORK_USES_BUNDLE: "NETWORK_USES_BUNDLE",
  WORKFLOW_TRIGGERS: "WORKFLOW_TRIGGERS",
  WORKFLOW_UPDATES_FIELD: "WORKFLOW_UPDATES_FIELD",
  APPROVAL_USES_FORMULA: "APPROVAL_USES_FORMULA",
  INSTANCE_OF: "INSTANCE_OF",
  REFERENCES_LABEL: "REFERENCES_LABEL",
  GRANTS_USER_PERMISSION: "GRANTS_USER_PERMISSION",
} as const;

export type RelType = (typeof REL_TYPES)[keyof typeof REL_TYPES];
