export const REL_TYPES = {
  READS_FIELD: "READS_FIELD",
  WRITES_FIELD: "WRITES_FIELD",
  CALLS: "CALLS",
  CALLS_DR: "CALLS_DR",
  EXTENDS: "EXTENDS",
  IMPLEMENTS: "IMPLEMENTS",
  REFERENCES: "REFERENCES",
  CONTAINS: "CONTAINS",
  USES_LWC: "USES_LWC",
  TRIGGERS_ON: "TRIGGERS_ON",
  GRANTS: "GRANTS",
  QUERIES: "QUERIES",
} as const;

export type RelType = (typeof REL_TYPES)[keyof typeof REL_TYPES];
